package aemet.vista;

import aemet.modelo.Control;
import java.awt.event.WindowEvent;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Miquel A. Fuster
 */
public class VentanaDeCarga extends javax.swing.JFrame {

    /**
     * Creates new form VentanaDeCarga
     */
    public VentanaDeCarga() {
        initComponents();
    }
    
    /**
     * Actualiza la BBDD desde datos de la AEMET
     */
    private void actualizarBBDD() {
        try {
            lblEventos.setText("Buscando nuevas estaciones en la AEMET ...");
            Control.actualizarEstaciones();
            lblEventos.setText("Actualizando las observaciones ...");
            Control.actualizarMediciones();
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, "No se pudo conectar con el servidor de la AEMET", "Error de conexión", JOptionPane.WARNING_MESSAGE);
            Logger.getLogger(VentanaDeCarga.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblImagen = new javax.swing.JLabel();
        lblEventos = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));

        lblImagen.setIcon(new javax.swing.ImageIcon(getClass().getResource("/estacion.jpg"))); // NOI18N

        lblEventos.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lblEventos.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(lblImagen)
                .addGap(0, 0, Short.MAX_VALUE))
            .addComponent(lblEventos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(lblImagen)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblEventos, javax.swing.GroupLayout.DEFAULT_SIZE, 14, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Genera el FORM de forma secuencial. Al terminar la inicialización termina la ventana.
     */
    public static void inicializar() {
        VentanaDeCarga v = new VentanaDeCarga();
        v.setLocationRelativeTo(null);
        v.setVisible(true);
        v.actualizarBBDD();
        v.setVisible(false);
        v.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
        v.dispatchEvent(new WindowEvent(v, WindowEvent.WINDOW_CLOSING));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel lblEventos;
    private javax.swing.JLabel lblImagen;
    // End of variables declaration//GEN-END:variables
}
